#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Download all icons from line-md collection with Chinese names

import requests
import json

# 中文名称映射表
chinese_names = {
    # Account
    "account": "账户",
    "account-add": "添加账户",
    "account-alert": "账户警告",
    "account-alert-loop": "账户警告循环",
    "account-delete": "删除账户",
    "account-remove": "移除账户",
    "account-small": "小账户",
    "log-in": "登录",
    "log-out": "退出",
    "login": "登录",
    "logout": "退出",
    "person": "人物",
    "person-add": "添加人物",
    "person-add-filled": "添加人物填充",
    "person-add-twotone": "添加人物双色",
    "person-filled": "人物填充",
    "person-off": "人物关闭",
    "person-off-filled": "人物关闭填充",
    "person-off-filled-loop": "人物关闭填充循环",
    "person-off-loop": "人物关闭循环",
    "person-off-twotone": "人物关闭双色",
    "person-off-twotone-loop": "人物关闭双色循环",
    "person-remove": "移除人物",
    "person-remove-filled": "移除人物填充",
    "person-remove-twotone": "移除人物双色",
    # Actions
    "check": "勾选",
    "check-all": "全选",
    "check-circle": "勾选圆形",
    "check-circle-filled": "勾选圆形填充",
    "check-circle-off": "勾选圆形关闭",
    "check-circle-off-filled": "勾选圆形关闭填充",
    "check-circle-off-twotone": "勾选圆形关闭双色",
    "check-circle-twotone": "勾选圆形双色",
    "check-list": "勾选列表",
    "check-list-2": "勾选列表2",
    "check-list-2-filled": "勾选列表2填充",
    "check-list-3": "勾选列表3",
    "check-list-3-filled": "勾选列表3填充",
    "close": "关闭",
    "close-circle": "关闭圆形",
    "close-circle-filled": "关闭圆形填充",
    "close-circle-off": "关闭圆形关闭",
    "close-circle-off-filled": "关闭圆形关闭填充",
    "close-circle-off-twotone": "关闭圆形关闭双色",
    "close-circle-twotone": "关闭圆形双色",
    "filter": "筛选",
    "filter-check": "筛选勾选",
    "filter-off": "筛选关闭",
    "flag": "旗帜",
    "flag-alt": "旗帜替代",
    "flag-alt-filled": "旗帜替代填充",
    "flag-filled": "旗帜填充",
    "flag-off": "旗帜关闭",
    "flag-off-filled": "旗帜关闭填充",
    "flag-off-twotone": "旗帜关闭双色",
    "flag-twotone": "旗帜双色",
    "minus": "减号",
    "minus-circle": "减号圆形",
    "minus-circle-filled": "减号圆形填充",
    "minus-circle-twotone": "减号圆形双色",
    "plus": "加号",
    "plus-circle": "加号圆形",
    "plus-circle-filled": "加号圆形填充",
    "plus-circle-twotone": "加号圆形双色",
    "redo": "重做",
    "redo-alt": "重做替代",
    "star": "星星",
    "star-filled": "星星填充",
    "star-filled-half": "星星填充一半",
    "star-filled-right-half": "星星右半填充",
    "star-off": "星星关闭",
    "star-off-filled": "星星关闭填充",
    "star-off-twotone": "星星关闭双色",
    "star-twotone": "星星双色",
    "star-twotone-half": "星星双色一半",
    "star-twotone-right-half": "星星右半双色",
    "undo": "撤销",
    "undo-alt": "撤销替代",
    # Alert
    "alert-circle": "警告圆形",
    "alert-circle-filled": "警告圆形填充",
    "alert-circle-twotone": "警告圆形双色",
    "alert-octagon": "警告八边形",
    "alert-octagon-filled": "警告八边形填充",
    "alert-octagon-twotone": "警告八边形双色",
    "alert-trian": "警告三角",
    "alert-trian-down": "警告三角向下",
    "alert-trian-filled": "警告三角填充",
    "alert-trian-twotone": "警告三角双色",
    "bell": "铃铛",
    "bell-alert": "铃铛警告",
    "bell-alert-loop": "铃铛警告循环",
    "bell-alert-twotone": "铃铛警告双色",
    "bell-alert-twotone-loop": "铃铛警告双色循环",
    "bell-off": "铃铛关闭",
    "bell-off-filled": "铃铛关闭填充",
    "bell-off-twotone": "铃铛关闭双色",
    "bell-twotone": "铃铛双色",
    "bell-twotone-alert": "铃铛双色警告",
    "bell-twotone-alert-loop": "铃铛双色警告循环",
    "info": "信息",
    "info-circle": "信息圆形",
    "info-circle-filled": "信息圆形填充",
    "info-circle-twotone": "信息圆形双色",
    "shield": "盾牌",
    "shield-check": "盾牌勾选",
    "shield-off": "盾牌关闭",
    "shield-off-filled": "盾牌关闭填充",
    "shield-off-twotone": "盾牌关闭双色",
    "shield-twotone": "盾牌双色",
    # Audio
    "audio": "音频",
    "audio-off": "音频关闭",
    "audio-off-twotone": "音频关闭双色",
    "audio-twotone": "音频双色",
    "disc": "唱片",
    "disc-off": "唱片关闭",
    "disc-off-twotone": "唱片关闭双色",
    "disc-twotone": "唱片双色",
    "headphones": "耳机",
    "headphones-off": "耳机关闭",
    "headphones-off-twotone": "耳机关闭双色",
    "headphones-twotone": "耳机双色",
    "mic": "麦克风",
    "mic-off": "麦克风关闭",
    "mic-off-twotone": "麦克风关闭双色",
    "mic-twotone": "麦克风双色",
    "music": "音乐",
    "music-off": "音乐关闭",
    "music-off-twotone": "音乐关闭双色",
    "music-twotone": "音乐双色",
    # Communication
    "chat": "聊天",
    "chat-bubble": "聊天气泡",
    "chat-bubble-off": "聊天气泡关闭",
    "chat-bubble-off-filled": "聊天气泡关闭填充",
    "chat-bubble-off-twotone": "聊天气泡关闭双色",
    "chat-bubble-twotone": "聊天气泡双色",
    "chat-check": "聊天勾选",
    "chat-check-twotone": "聊天勾选双色",
    "chat-off": "聊天关闭",
    "chat-off-filled": "聊天关闭填充",
    "chat-off-twotone": "聊天关闭双色",
    "chat-round": "聊天圆形",
    "chat-round-check": "聊天圆形勾选",
    "chat-round-check-twotone": "聊天圆形勾选双色",
    "chat-round-off": "聊天圆形关闭",
    "chat-round-off-filled": "聊天圆形关闭填充",
    "chat-round-off-twotone": "聊天圆形关闭双色",
    "chat-round-twotone": "聊天圆形双色",
    "chat-twotone": "聊天双色",
    "email": "邮件",
    "email-check": "邮件勾选",
    "email-check-twotone": "邮件勾选双色",
    "email-open": "邮件打开",
    "email-open-alt": "邮件打开替代",
    "email-open-alt-twotone": "邮件打开替代双色",
    "email-opened": "已打开邮件",
    "email-opened-alt": "已打开邮件替代",
    "email-opened-alt-twotone": "已打开邮件替代双色",
    "email-twotone": "邮件双色",
    "send": "发送",
    "send-check": "发送勾选",
    "send-check-twotone": "发送勾选双色",
    "send-twotone": "发送双色",
    # Content
    "archive": "归档",
    "archive-filled": "归档填充",
    "archive-twotone": "归档双色",
    "book": "书本",
    "book-open": "打开书本",
    "book-open-twotone": "打开书本双色",
    "book-twotone": "书本双色",
    "bookmark": "书签",
    "bookmark-filled": "书签填充",
    "bookmark-twotone": "书签双色",
    "calendar": "日历",
    "calendar-check": "日历勾选",
    "calendar-check-twotone": "日历勾选双色",
    "calendar-clock": "日历时钟",
    "calendar-clock-twotone": "日历时钟双色",
    "calendar-filled": "日历填充",
    "calendar-remove": "日历移除",
    "calendar-remove-twotone": "日历移除双色",
    "calendar-twotone": "日历双色",
    "folder": "文件夹",
    "folder-download": "文件夹下载",
    "folder-download-twotone": "文件夹下载双色",
    "folder-filled": "文件夹填充",
    "folder-image": "文件夹图片",
    "folder-image-twotone": "文件夹图片双色",
    "folder-music": "文件夹音乐",
    "folder-music-twotone": "文件夹音乐双色",
    "folder-open": "打开文件夹",
    "folder-open-filled": "打开文件夹填充",
    "folder-open-twotone": "打开文件夹双色",
    "folder-twotone": "文件夹双色",
    "folder-upload": "文件夹上传",
    "folder-upload-twotone": "文件夹上传双色",
    "folder-video": "文件夹视频",
    "folder-video-twotone": "文件夹视频双色",
    "inbox": "收件箱",
    "inbox-filled": "收件箱填充",
    "inbox-twotone": "收件箱双色",
    "page": "页面",
    "page-filled": "页面填充",
    "page-twotone": "页面双色",
    "receipt": "收据",
    "receipt-text": "收据文本",
    "receipt-text-twotone": "收据文本双色",
    "receipt-twotone": "收据双色",
    "ticket": "票据",
    "ticket-filled": "票据填充",
    "ticket-twotone": "票据双色",
    # Device
    "battery": "电池",
    "battery-charging": "电池充电",
    "battery-charging-twotone": "电池充电双色",
    "battery-empty": "电池空",
    "battery-empty-twotone": "电池空双色",
    "battery-full": "电池满",
    "battery-full-twotone": "电池满双色",
    "battery-low": "电池低",
    "battery-low-twotone": "电池低双色",
    "battery-medium": "电池中等",
    "battery-medium-twotone": "电池中等双色",
    "battery-twotone": "电池双色",
    "bluetooth": "蓝牙",
    "bluetooth-off": "蓝牙关闭",
    "bluetooth-off-twotone": "蓝牙关闭双色",
    "bluetooth-twotone": "蓝牙双色",
    "cellphone": "手机",
    "cellphone-arrow-down": "手机向下箭头",
    "cellphone-arrow-down-twotone": "手机向下箭头双色",
    "cellphone-arrow-up": "手机向上箭头",
    "cellphone-arrow-up-twotone": "手机向上箭头双色",
    "cellphone-screenshot": "手机截图",
    "cellphone-screenshot-twotone": "手机截图双色",
    "cellphone-twotone": "手机双色",
    "hard-drive": "硬盘",
    "hard-drive-twotone": "硬盘双色",
    "monitor": "显示器",
    "monitor-screenshot": "显示器截图",
    "monitor-screenshot-filled": "显示器截图填充",
    "monitor-screenshot-twotone": "显示器截图双色",
    "monitor-small": "小显示器",
    "monitor-small-filled": "小显示器填充",
    "monitor-small-off": "小显示器关闭",
    "monitor-small-off-filled": "小显示器关闭填充",
    "monitor-small-off-twotone": "小显示器关闭双色",
    "monitor-small-twotone": "小显示器双色",
    "monitor-twotone": "显示器双色",
    "security": "安全",
    "security-filled": "安全填充",
    "security-off": "安全关闭",
    "security-off-filled": "安全关闭填充",
    "security-off-twotone": "安全关闭双色",
    "security-twotone": "安全双色",
    "tablet": "平板",
    "tablet-arrow-down": "平板向下箭头",
    "tablet-arrow-down-twotone": "平板向下箭头双色",
    "tablet-arrow-up": "平板向上箭头",
    "tablet-arrow-up-twotone": "平板向上箭头双色",
    "tablet-off": "平板关闭",
    "tablet-off-twotone": "平板关闭双色",
    "tablet-screenshot": "平板截图",
    "tablet-screenshot-twotone": "平板截图双色",
    "tablet-twotone": "平板双色",
    # Editor
    "align-center": "居中对齐",
    "align-left": "左对齐",
    "align-right": "右对齐",
    "bold": "粗体",
    "code": "代码",
    "code-twotone": "代码双色",
    "columns": "列",
    "edit": "编辑",
    "edit-full": "完全编辑",
    "edit-full-twotone": "完全编辑双色",
    "edit-twotone": "编辑双色",
    "format-clear": "清除格式",
    "format-list-bulleted": "项目符号列表",
    "format-list-numbered": "编号列表",
    "hash": "哈希",
    "heading-1": "标题1",
    "heading-2": "标题2",
    "heading-3": "标题3",
    "indent-decrease": "减少缩进",
    "indent-increase": "增加缩进",
    "italic": "斜体",
    "link": "链接",
    "list": "列表",
    "list-2": "列表2",
    "list-3": "列表3",
    "list-3-filled": "列表3填充",
    "palette": "调色板",
    "paperclip": "回形针",
    "paperclip-off": "回形针关闭",
    "paperclip-off-twotone": "回形针关闭双色",
    "paperclip-twotone": "回形针双色",
    "pencil": "铅笔",
    "pencil-alt": "铅笔替代",
    "pencil-alt-twotone": "铅笔替代双色",
    "pencil-twotone": "铅笔双色",
    "quote": "引用",
    "strikethrough": "删除线",
    "subscript": "下标",
    "superscript": "上标",
    "text": "文本",
    "underline": "下划线",
    # Files
    "file": "文件",
    "file-check": "文件勾选",
    "file-check-twotone": "文件勾选双色",
    "file-code": "代码文件",
    "file-code-twotone": "代码文件双色",
    "file-image": "图片文件",
    "file-image-twotone": "图片文件双色",
    "file-music": "音乐文件",
    "file-music-twotone": "音乐文件双色",
    "file-off": "文件关闭",
    "file-off-filled": "文件关闭填充",
    "file-off-twotone": "文件关闭双色",
    "file-text": "文本文件",
    "file-text-twotone": "文本文件双色",
    "file-video": "视频文件",
    "file-video-twotone": "视频文件双色",
    "file-twotone": "文件双色",
    "folder-download": "文件夹下载",
    "folder-upload": "文件夹上传",
    # Hardware
    "keyboard": "键盘",
    "keyboard-off": "键盘关闭",
    "keyboard-off-twotone": "键盘关闭双色",
    "keyboard-twotone": "键盘双色",
    "mouse": "鼠标",
    "mouse-off": "鼠标关闭",
    "mouse-off-twotone": "鼠标关闭双色",
    "mouse-twotone": "鼠标双色",
    "printer": "打印机",
    "printer-off": "打印机关闭",
    "printer-off-twotone": "打印机关闭双色",
    "printer-twotone": "打印机双色",
    # Image
    "camera": "相机",
    "camera-off": "相机关闭",
    "camera-off-twotone": "相机关闭双色",
    "camera-twotone": "相机双色",
    "image": "图片",
    "image-off": "图片关闭",
    "image-off-twotone": "图片关闭双色",
    "image-twotone": "图片双色",
    "image-plus": "添加图片",
    "image-plus-twotone": "添加图片双色",
    "images": "图片集",
    "images-off": "图片集关闭",
    "images-off-twotone": "图片集关闭双色",
    "images-twotone": "图片集双色",
    "panorama": "全景",
    "panorama-horizontal": "横向全景",
    "panorama-horizontal-twotone": "横向全景双色",
    "panorama-twotone": "全景双色",
    "zoom-in": "放大",
    "zoom-out": "缩小",
    # Maps
    "compass": "指南针",
    "compass-off": "指南针关闭",
    "compass-off-twotone": "指南针关闭双色",
    "compass-twotone": "指南针双色",
    "map": "地图",
    "map-marker": "地图标记",
    "map-marker-alt": "地图标记替代",
    "map-marker-alt-off": "地图标记替代关闭",
    "map-marker-alt-off-filled": "地图标记替代关闭填充",
    "map-marker-alt-off-filled-loop": "地图标记替代关闭填充循环",
    "map-marker-alt-off-loop": "地图标记替代关闭循环",
    "map-marker-alt-off-twotone": "地图标记替代关闭双色",
    "map-marker-alt-off-twotone-loop": "地图标记替代关闭双色循环",
    "map-marker-off": "地图标记关闭",
    "map-marker-off-filled": "地图标记关闭填充",
    "map-marker-off-twotone": "地图标记关闭双色",
    "map-marker-twotone": "地图标记双色",
    "navigation": "导航",
    "navigation-twotone": "导航双色",
    # Navigation
    "arrow-down": "向下箭头",
    "arrow-left": "向左箭头",
    "arrow-right": "向右箭头",
    "arrow-up": "向上箭头",
    "arrows-horizontal": "水平箭头",
    "arrows-long-diagonal": "长对角箭头",
    "arrows-long-diagonal-rotated": "旋转长对角箭头",
    "arrows-vertical": "垂直箭头",
    "chevron-down": "向下雪佛龙",
    "chevron-left": "向左雪佛龙",
    "chevron-right": "向右雪佛龙",
    "chevron-up": "向上雪佛龙",
    "corner-down-left": "左下拐角",
    "corner-down-right": "右下拐角",
    "corner-left-down": "左下方拐角",
    "corner-left-up": "左上方拐角",
    "corner-right-down": "右下方拐角",
    "corner-right-up": "右上方拐角",
    "corner-up-left": "左上拐角",
    "corner-up-right": "右上拐角",
    "home": "首页",
    "home-alt": "首页替代",
    "home-alt-twotone": "首页替代双色",
    "home-md": "首页MD",
    "home-md-alt": "首页MD替代",
    "home-md-alt-twotone": "首页MD替代双色",
    "home-twotone": "首页双色",
    "menu": "菜单",
    "menu-burger": "汉堡菜单",
    "menu-burger-off": "汉堡菜单关闭",
    "menu-dots-horizontal": "水平点菜单",
    "menu-dots-vertical": "垂直点菜单",
    "move": "移动",
    "rotate-ccw": "逆时针旋转",
    "rotate-cw": "顺时针旋转",
    "settings": "设置",
    "settings-twotone": "设置双色",
    "sidebar": "侧边栏",
    "sidebar-left": "左侧边栏",
    "sidebar-right": "右侧边栏",
    "view-grid": "网格视图",
    "view-grid-2": "网格视图2",
    "view-grid-3": "网格视图3",
    "view-list": "列表视图",
    # Notification
    "badge": "徽章",
    "badge-check": "徽章勾选",
    "badge-check-twotone": "徽章勾选双色",
    "badge-people": "徽章人物",
    "badge-people-twotone": "徽章人物双色",
    "badge-twotone": "徽章双色",
    "broadcast": "广播",
    "broadcast-twotone": "广播双色",
    "rss": "RSS",
    "rss-twotone": "RSS双色",
    # Social
    "share": "分享",
    "share-all": "全部分享",
    "share-all-twotone": "全部分享双色",
    "share-twotone": "分享双色",
    "user-check": "用户勾选",
    "user-check-twotone": "用户勾选双色",
    "user-minus": "用户减号",
    "user-minus-twotone": "用户减号双色",
    "user-plus": "用户加号",
    "user-plus-twotone": "用户加号双色",
    "users": "用户组",
    "users-twotone": "用户组双色",
    # Weather
    "moon": "月亮",
    "moon-alt": "月亮替代",
    "moon-alt-filled": "月亮替代填充",
    "moon-alt-filled-loop": "月亮替代填充循环",
    "moon-alt-loop": "月亮替代循环",
    "moon-alt-off": "月亮替代关闭",
    "moon-alt-off-filled": "月亮替代关闭填充",
    "moon-alt-off-filled-loop": "月亮替代关闭填充循环",
    "moon-alt-off-loop": "月亮替代关闭循环",
    "moon-alt-off-twotone": "月亮替代关闭双色",
    "moon-alt-off-twotone-loop": "月亮替代关闭双色循环",
    "moon-alt-to-sunny-outline-loop-transition": "月亮替代到晴天轮廓循环过渡",
    "moon-alt-twotone": "月亮替代双色",
    "moon-alt-twotone-loop": "月亮替代双色循环",
    "moon-filled": "月亮填充",
    "moon-filled-alt-to-sunny-filled-loop-transition": "月亮填充替代到晴天填充循环过渡",
    "moon-filled-loop": "月亮填充循环",
    "moon-filled-to-sunny-filled-loop-transition": "月亮填充到晴天填充循环过渡",
    "moon-filled-to-sunny-filled-transition": "月亮填充到晴天填充过渡",
    "moon-loop": "月亮循环",
    "moon-off": "月亮关闭",
    "moon-off-filled": "月亮关闭填充",
    "moon-off-filled-loop": "月亮关闭填充循环",
    "moon-off-loop": "月亮关闭循环",
    "moon-off-twotone": "月亮关闭双色",
    "moon-off-twotone-loop": "月亮关闭双色循环",
    "moon-rising": "月亮升起",
    "moon-rising-alt": "月亮升起替代",
    "moon-rising-alt-filled": "月亮升起替代填充",
    "moon-rising-alt-filled-loop": "月亮升起替代填充循环",
    "moon-rising-alt-loop": "月亮升起替代循环",
    "moon-rising-alt-twotone": "月亮升起替代双色",
    "moon-rising-alt-twotone-loop": "月亮升起替代双色循环",
    "moon-rising-filled": "月亮升起填充",
    "moon-rising-filled-loop": "月亮升起填充循环",
    "moon-rising-loop": "月亮升起循环",
    "moon-rising-twotone": "月亮升起双色",
    "moon-rising-twotone-loop": "月亮升起双色循环",
    "moon-simple": "月亮简单",
    "moon-simple-filled": "月亮简单填充",
    "moon-simple-off": "月亮简单关闭",
    "moon-simple-off-filled": "月亮简单关闭填充",
    "moon-simple-off-twotone": "月亮简单关闭双色",
    "moon-simple-twotone": "月亮简单双色",
    "moon-to-sunny-outline-loop-transition": "月亮到晴天轮廓循环过渡",
    "moon-to-sunny-outline-transition": "月亮到晴天轮廓过渡",
    "moon-twotone": "月亮双色",
    "moon-twotone-loop": "月亮双色循环",
    "sun-rising": "太阳升起",
    "sun-rising-filled": "太阳升起填充",
    "sun-rising-filled-loop": "太阳升起填充循环",
    "sun-rising-loop": "太阳升起循环",
    "sun-rising-twotone": "太阳升起双色",
    "sun-rising-twotone-loop": "太阳升起双色循环",
    "sunny": "晴天",
    "sunny-filled": "晴天填充",
    "sunny-filled-loop": "晴天填充循环",
    "sunny-filled-loop-to-moon-filled-alt-loop-transition": "晴天填充循环到月亮填充替代循环过渡",
    "sunny-filled-loop-to-moon-filled-loop-transition": "晴天填充循环到月亮填充循环过渡",
    "sunny-filled-loop-to-moon-filled-transition": "晴天填充循环到月亮填充过渡",
    "sunny-loop": "晴天循环",
    "sunny-off": "晴天关闭",
    "sunny-off-filled": "晴天关闭填充",
    "sunny-off-filled-loop": "晴天关闭填充循环",
    "sunny-off-loop": "晴天关闭循环",
    "sunny-off-twotone": "晴天关闭双色",
    "sunny-off-twotone-loop": "晴天关闭双色循环",
    "sunny-outline-to-moon-alt-loop-transition": "晴天轮廓到月亮替代循环过渡",
    "sunny-outline-to-moon-loop-transition": "晴天轮廓到月亮循环过渡",
    "sunny-outline-to-moon-transition": "晴天轮廓到月亮过渡",
    "sunny-twotone": "晴天双色",
    "sunny-twotone-loop": "晴天双色循环",
    "weather-cloudy-loop": "多云循环天气",
    # Default fallback
    "cloud": "云",
    "cloud-alt": "云替代",
    "cloud-alt-braces": "云替代括号",
    "cloud-alt-braces-loop": "云替代括号循环",
    "cloud-alt-download": "云替代下载",
    "cloud-alt-download-filled": "云替代下载填充",
    "cloud-alt-download-filled-loop": "云替代下载填充循环",
    "cloud-alt-download-loop": "云替代下载循环",
    "cloud-alt-filled": "云替代填充",
    "cloud-alt-filled-loop": "云替代填充循环",
    "cloud-alt-off": "云替代关闭",
    "cloud-alt-off-loop": "云替代关闭循环",
    "cloud-alt-loop": "云替代循环",
    "cloud-alt-print": "云替代打印",
    "cloud-alt-print-filled": "云替代打印填充",
    "cloud-alt-print-loop": "云替代打印循环",
    "cloud-alt-tags": "云替代标签",
    "cloud-alt-tags-filled": "云替代标签填充",
    "cloud-alt-tags-loop": "云替代标签循环",
    "cloud-alt-upload": "云替代上传",
    "cloud-alt-upload-filled": "云替代上传填充",
    "cloud-alt-upload-loop": "云替代上传循环",
    "cloud-download": "云下载",
    "cloud-download-outline": "云下载轮廓",
    "cloud-download-outline-loop": "云下载轮廓循环",
    "cloud-off": "云关闭",
    "cloud-off-outline": "云关闭轮廓",
    "cloud-off-outline-loop": "云关闭轮廓循环",
    "cloud-print": "云打印",
    "cloud-print-outline": "云打印轮廓",
    "cloud-print-outline-loop": "云打印轮廓循环",
    "cloud-tags": "云标签",
    "cloud-upload": "云上传",
    "cloud-upload-outline": "云上传轮廓",
    "cloud-upload-outline-loop": "云上传轮廓循环",
    "link-off": "链接关闭",
    "refresh": "刷新",
    "refresh-cw": "顺时针刷新",
    "upload": "上传",
    "download": "下载",
    "external-link": "外部链接",
    "eye": "眼睛",
    "eye-off": "眼睛关闭",
    "eye-off-twotone": "眼睛关闭双色",
    "eye-twotone": "眼睛双色",
    "lock": "锁",
    "lock-open": "打开锁",
    "lock-open-twotone": "打开锁双色",
    "lock-twotone": "锁双色",
    "unlock": "解锁",
}


def get_chinese_name(name):
    """获取图标中文名称"""
    return chinese_names.get(name, name)


def main():
    print("Downloading line-md icons from Iconify API...")

    # Get icon list from collection API
    url = "https://api.iconify.design/collection?prefix=line-md"
    response = requests.get(url)

    if response.status_code != 200:
        print("Failed to download:", response.status_code)
        return

    data = response.json()

    # Get all icon names from categories
    all_icons = []
    all_categories = {}
    categories = data.get("categories", {})
    for category_name, icon_list in categories.items():
        if isinstance(icon_list, list):
            all_icons.extend(icon_list)
            for icon_name in icon_list:
                all_categories[icon_name] = category_name

    icons = all_icons
    print(
        "Found {} total icons across {} categories".format(len(icons), len(categories))
    )

    # Generate TypeScript file
    with open("src/data/lineMdIcons.ts", "w", encoding="utf-8") as f:
        f.write("export interface Icon {\n")
        f.write("  name: string;\n")
        f.write("  chineseName: string;\n")
        f.write("  category: string;\n")
        f.write("  svg: string;\n")
        f.write("}\n\n")
        f.write("export const lineMdIcons: Icon[] = [\n")

        count = 0
        for name in icons:
            if count >= 500:
                break

            # Get SVG from API
            svg_url = "https://api.iconify.design/line-md/{}.svg".format(name)
            svg_response = requests.get(svg_url)

            if svg_response.status_code == 200:
                svg = svg_response.text.strip()
                # Clean up SVG and set fixed size to 24x24
                svg = svg.replace("\n", " ").replace("\r", " ")
                svg = " ".join(svg.split())
                # Replace width and height from 1em to 24px
                svg = svg.replace('width="1em" height="1em"', 'width="24" height="24"')

                # Get Chinese name and category
                chinese_name = get_chinese_name(name)
                category = all_categories.get(name, "未分类")

                f.write(
                    '  {{ name: "{}", chineseName: "{}", category: "{}", svg: `{}` }},\n'.format(
                        name, chinese_name, category, svg
                    )
                )
                count += 1

                if count % 50 == 0:
                    print("Downloaded {} icons...".format(count))

            # Rate limiting
            if count % 10 == 0:
                import time

                time.sleep(0.1)

        f.write("]\n")

    print("Done! Generated {} icons to src/data/lineMdIcons.ts".format(count))


if __name__ == "__main__":
    main()
